# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95b4126d0a01b3dc057d55130f14b3b582e9a5ef470372964667d4343ff8359806e48afdc25ad972bc2c9d8ab8c772aead00631930b2ef3c528e7e20bb2032fa

test:
  secret_key_base: 5a18d1397ddb103efbd59e4e4dae9c7c38ad61945f8e3a59fca9ff469778d78ace15235ab107a1ba2b4e15b35790665a58df460c8056926a7b61500811c5b64b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
